### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by paocorrales** [paocorrales/paqueteprueba#1]
# Checklist para revisar el paquete

- [ ] Estructura del paquete
- [ ] Repositorio local
- [ ] Repositorio remoto

## DESCRIPTION

- [ ] Título
- [ ] Descripción

## Funciones y datos

- [ ] (al menos) 3 funciones
- [ ] (al menos) 1 set de datos

## Documentación

- Todas las funciones y datos están documentados
- README completo
- Incluye una viñeta que explica como usar las funciones
- El paquete tiene una página web

## Tests

- El paquete tiene tests que cubren al menos el 75% del código de las funciones
- El paquete tiene una GitHub action que revisa la covertura de los tests
- El paquete pasa R CMD checks
- El paquete tiene una GitHub action que chequea el paquete en distintos sistemas operativos

## Otros

- [ ] Incluye una licencia
- [ ] El README incluye instrucciones sobre como colaborar con el proyecto

**Comment by paocorrales** [comment]
(ejemplo de checklist para paquetes, me falta algo?)
